# Generated by Django 5.1.3 on 2024-11-18 12:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=users.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
