# Generated by Django 5.1.3 on 2024-11-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_privatechat_privatemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='content',
            new_name='message',
        ),
    ]
